-- 262. 行程和用户
-- SUM,COUNT,ROUND函数的用法，先去除被禁止的用户，然后统计取消订单的数目，计算比率
SELECT T.REQUEST_AT AS `DAY`, 
	ROUND(SUM(IF(T.STATUS = 'COMPLETED',0,1))/COUNT(T.STATUS),2) AS `CANCELLATION RATE`
FROM TRIPS AS T
WHERE 
T.CLIENT_ID NOT IN (
	SELECT USERS_ID FROM USERS WHERE BANNED = 'YES'
)
AND
T.DRIVER_ID NOT IN (
	SELECT USERS_ID FROM USERS WHERE BANNED = 'YES'
)
AND T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY T.REQUEST_AT

SELECT 
T.REQUEST_AT AS `DAY`, 
ROUND(SUM(IF(T.STATUS = 'COMPLETED',0,1))/COUNT(T.STATUS),2) AS `CANCELLATION RATE`
FROM
    (SELECT A.CLIENT_ID,B.BANNED AS C_BAN,A.DRIVER_ID,C.BANNED AS D_BAN, A.STATUS,A.REQUEST_AT 
    FROM TRIPS A 
        LEFT JOIN USERS B ON A.CLIENT_ID=B.USERS_ID 
        LEFT JOIN USERS C ON A.DRIVER_ID=C.USERS_ID) T
WHERE T.C_BAN='NO' 
AND D_BAN='NO' 
AND T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY T.REQUEST_AT
