-- 185. 部门工资前三高的所有员工
    -- 方法1
SELECT C.DEPARTMENT,C.EMPLOYEE,C.SALARY FROM (
    SELECT B.NAME AS DEPARTMENT,A.NAME AS EMPLOYEE,SALARY,DENSE_RANK()OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RK FROM EMPLOYEE A,DEPARTMENT B WHERE A.DEPARTMENTID=B.ID
) C WHERE C.RK<=3
    -- 方法2
SELECT
    d.Name AS 'Department', e1.Name AS 'Employee', e1.Salary
FROM
    Employee e1
        JOIN
    Department d ON e1.DepartmentId = d.Id
WHERE
    (SELECT
        COUNT(DISTINCT e2.Salary)
    FROM
        Employee e2
    WHERE
        e2.Salary > e1.Salary
            AND e1.DepartmentId = e2.DepartmentId
    )<3;

-- 196. 删除重复的电子邮箱
DELETE FROM PERSON WHERE ID NOT IN (SELECT T.ID FROM (SELECT MIN(ID) AS ID FROM PERSON GROUP BY EMAIL)T)

DELETE P1 FROM PERSON P1,PERSON P2 WHERE P1.EMAIL=P2.EMAIL AND P1.ID > P2.ID

-- 197. 上升的温度
SELECT A.ID AS 'ID' FROM WEATHER A INNER JOIN WEATHER B ON DATEDIFF(A.RECORDDATE, B.RECORDDATE) = 1 AND A.TEMPERATURE > B.TEMPERATURE
-- DATEDIFF(PARAM1,PARAM2) 函数返回两个日期之间的天数。PARAM1>PARAM2 返回负数，PARAM1<PARAM2 返回正数

SELECT W2.ID FROM WEATHER W1 LEFT JOIN WEATHER W2 ON DATE_ADD(W1.RECORDDATE, INTERVAL 1 DAY) = W2.RECORDDATE
WHERE W1.TEMPERATURE < W2.TEMPERATURE