-- 181. 超过经理收入的员工
SELECT A.NAME AS EMPLOYEE FROM EMPLOYEE A LEFT JOIN EMPLOYEE B ON A.MANAGERID=B.ID WHERE A.SALARY > B.SALARY


-- 182. 查找重复的电子邮箱
SELECT EMAIL FROM PERSON GROUP BY EMAIL HAVING COUNT(*)>=2

SELECT DISTINCT A.EMAIL FROM PERSON A,PERSON B WHERE A.EMAIL=B.EMAIL AND A.ID!=B.ID

SELECT A.EMAIL FROM (SELECT COUNT(1) AS CC,EMAIL FROM PERSON GROUP BY EMAIL)A WHERE A.CC>1



-- 183. 从不订购的客户
SELECT NAME AS CUSTOMERS FROM CUSTOMERS A LEFT JOIN ORDERS B ON A.ID=B.CUSTOMERID WHERE B.ID IS NULL

SELECT NAME AS CUSTOMERS FROM CUSTOMERS A WHERE A.ID NOT IN (SELECT CUSTOMERID FROM ORDERS)

SELECT A.NAME AS CUSTOMERS FROM CUSTOMERS A WHERE NOT EXISTS (SELECT 1 FROM ORDERS B WHERE B.CUSTOMERID=A.ID)
--EXISTS用于检查子查询是否至少会返回一行数据，该子查询实际上并不返回任何数据，而是返回值True或False