-- 620. 有趣的电影
    SELECT * FROM CINEMA WHERE MOD(ID, 2) = 1 AND DESCRIPTION != 'BORING'ORDER BY RATING DESC

-- 626. 换座位
    SELECT
        (CASE 
            WHEN MOD(ID,2) !=0 AND COUNTS != ID THEN ID+1
            WHEN MOD(ID,2) !=0 AND COUNTS = ID THEN ID
        ELSE ID-1
        END) AS ID,
        STUDENT
    FROM SEAT,(SELECT COUNT(*) AS COUNTS FROM SEAT) AS SEAT_COUNTS
    ORDER BY ID ASC
    
-- 627. 变更性别
    --方法一：
    UPDATE SALARY SET SEX= CASE WHEN SEX='M' THEN 'F' ELSE 'M' END

    --方法二：
    UPDATE SALARY SET SEX=IF(SEX='F','M','F')